{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aaf06053-3c3b-4281-82bd-d5554a627cbd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Load the dataset\n",
    "data = pd.read_csv('individual_python_data.csv')\n",
    "\n",
    "# Set the title of the Streamlit dashboard\n",
    "st.title('Import-Export Data Dashboard')\n",
    "\n",
    "# Create subheader for each graph\n",
    "st.subheader('1. Histogram: Distribution of Quantity and Value')\n",
    "\n",
    "# Histogram: Distribution of Quantity and Value\n",
    "fig, ax = plt.subplots(1, 2, figsize=(12, 5))\n",
    "\n",
    "ax[0].hist(data['Quantity'], bins=20, color='skyblue', edgecolor='black')\n",
    "ax[0].set_title('Distribution of Quantity')\n",
    "ax[0].set_xlabel('Quantity')\n",
    "ax[0].set_ylabel('Frequency')\n",
    "\n",
    "ax[1].hist(data['Value'], bins=20, color='salmon', edgecolor='black')\n",
    "ax[1].set_title('Distribution of Value')\n",
    "ax[1].set_xlabel('Value')\n",
    "ax[1].set_ylabel('Frequency')\n",
    "\n",
    "st.pyplot(fig)\n",
    "\n",
    "# Bar Chart: Total quantity per country for Import/Export\n",
    "st.subheader('2. Bar Chart: Total Quantity by Country (Import vs Export)')\n",
    "\n",
    "import_export_summary = data.groupby(['Country', 'Import_Export'])['Quantity'].sum().unstack()\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "import_export_summary.plot(kind='bar', stacked=True, ax=ax)\n",
    "ax.set_title('Total Quantity by Country (Import vs Export)')\n",
    "ax.set_xlabel('Country')\n",
    "ax.set_ylabel('Total Quantity')\n",
    "ax.set_xticklabels(import_export_summary.index, rotation=90)\n",
    "\n",
    "st.pyplot(fig)\n",
    "\n",
    "# Box Plot: Distribution of Values based on Import/Export\n",
    "st.subheader('3. Box Plot: Distribution of Value by Import/Export')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8, 6))\n",
    "data.boxplot(column='Value', by='Import_Export', grid=False, ax=ax)\n",
    "ax.set_title('Distribution of Value by Import/Export')\n",
    "ax.set_xlabel('Import/Export')\n",
    "ax.set_ylabel('Value')\n",
    "plt.suptitle('')\n",
    "\n",
    "st.pyplot(fig)\n",
    "\n",
    "# Pie Chart: Share of different shipping methods\n",
    "st.subheader('4. Pie Chart: Share of Different Shipping Methods')\n",
    "\n",
    "shipping_method_counts = data['Shipping_Method'].value_counts()\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(6, 6))\n",
    "ax.pie(shipping_method_counts, labels=shipping_method_counts.index, autopct='%1.1f%%', startangle=90, \n",
    "       colors=['lightcoral', 'lightblue', 'lightgreen'])\n",
    "ax.set_title('Share of Different Shipping Methods')\n",
    "\n",
    "st.pyplot(fig)\n",
    "\n",
    "# Scatter Plot: Relationship between Weight and Value for Import/Export\n",
    "st.subheader('5. Scatter Plot: Weight vs Value for Import and Export')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8, 6))\n",
    "for imp_exp in data['Import_Export'].unique():\n",
    "    subset = data[data['Import_Export'] == imp_exp]\n",
    "    ax.scatter(subset['Weight'], subset['Value'], label=imp_exp, alpha=0.7)\n",
    "\n",
    "ax.set_title('Weight vs Value for Import and Export')\n",
    "ax.set_xlabel('Weight')\n",
    "ax.set_ylabel('Value')\n",
    "ax.legend(title=\"Import/Export\")\n",
    "\n",
    "st.pyplot(fig)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
